# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b159271ef04c70b075beb5b43dee83262212b343970a89bce47384539d4972fbbd0f428240728bfa29914339642c6e123d3358705e56c3b4a11534938bf5bbf8

test:
  secret_key_base: eca5dc8159a8b6c98700e170ddeb6ebf94fd7ccd1366932e71c9427719a90487f1efc6f8f246940e5cc0d57e3fbf24e54b00d0cd3b2811ea99b9b32a1614f208

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
